name: Push-to-EC2

# Trigger deployment only on push to QA branch
on:
  push:
    branches:
      - QA

jobs:
  deploy:
    name: Deploy to EC2 on QA branch push
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: ".git*,.github*"

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo mkdir -p ${{ secrets.TARGET_DIR }}
            sudo chown -R $USER:$USER ${{ secrets.TARGET_DIR }}
            sudo chmod -R 755 ${{ secrets.TARGET_DIR }}
            cd /home/QA
            sudo mv * /var/www/html
